<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/2_1_3_Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy intellekt Praktikum**
Ma'lumotlar tahlili
#2.1. Numpy kutubxonasini chiqarib olish

In [1]:
import numpy as np

#Massivga yo'naltirilgan dasturlash

Matematik va Statistik usullarni qo'llash

In [3]:
arr = np.random.randn(5, 4) # (5, 4) o'lchovli massiv(random)
arr

array([[-0.03785621,  2.62141299, -1.23509531,  1.67527942],
       [-0.58188294, -0.80646885, -1.25407452, -0.2809117 ],
       [ 0.58918982,  1.38733499,  0.73690039,  1.27485525],
       [-1.79698353,  0.29601085, -0.87373448,  0.78407431],
       [ 1.24364796, -2.58499235, -0.14619036,  0.79662313]])

`sum` methodi

In [4]:
arr.sum()  # arr barcha elementlarini yig'indisini hisoblab beradi

1.807138865721154

In [5]:
#ikkinchi usul
np.sum(arr)

1.807138865721154

In [6]:
arr.sum(axis=1) # qator yig'indi

array([ 3.0237409 , -2.92333801,  3.98828045, -1.59063285, -0.69091162])

In [7]:
arr.sum(axis=0) # ustun yig'indi

array([-0.58388491,  0.91329764, -2.77219427,  4.2499204 ])

`mean` methodi 

In [9]:
data = np.arange(6) 
data

array([0, 1, 2, 3, 4, 5])

In [10]:
mean = np.sum(data)/len(data)
mean

2.5

`numpy` mean 

In [12]:
np.mean(data)

2.5

In [13]:
data.mean()

2.5

In [14]:
arr

array([[-0.03785621,  2.62141299, -1.23509531,  1.67527942],
       [-0.58188294, -0.80646885, -1.25407452, -0.2809117 ],
       [ 0.58918982,  1.38733499,  0.73690039,  1.27485525],
       [-1.79698353,  0.29601085, -0.87373448,  0.78407431],
       [ 1.24364796, -2.58499235, -0.14619036,  0.79662313]])

In [15]:
np.mean(arr) # arr o'rtacha qiymati 

0.0903569432860577

In [17]:
#ikkinchi usul
arr.mean()

0.0903569432860577

In [18]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymat qaytaradi

array([ 0.75593522, -0.7308345 ,  0.99707011, -0.39765821, -0.1727279 ])

In [19]:
arr.mean(axis=0)

array([-0.11677698,  0.18265953, -0.55443885,  0.84998408])

In [20]:
arr2 = np.arange(11)

In [21]:
arr2.mean()

5.0

In [22]:
data

array([0, 1, 2, 3, 4, 5])

`cumsum` methodi

In [23]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15])