<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/2_1_3_Arr_Or_Pr_1_Logical_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Ma'lumotlar tahlili**


#NumPy kutubxonasi bilan ishlash

In [ ]:
import numpy as np

2.1.3 Massivga yo'naltirilgan dasturlash 

#Mantiqiy shart operatorlarini massiv operatori sifatida qo'llash 

Shart operatorlari sifatida `where` dan foydalanish

Tassavur qiling bizda 2ta ma'lumotlar(massivlar) mavjud bular: `xarr` , `yarr`. agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan va aksincha `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
#Massivlar
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5]) #xarr
yarr= np.array([2.1, 2.2, 2.3, 2.4, 2.5]) #yarr

In [ ]:
#shart
cond = np.array([True, False, True, True, False])

In [ ]:
#where
result = np.where(cond, xarr, yarr) 
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr=np.random.randn(4, 4) #(4, 4) Taxminiy massiv
arr

array([[ 1.49247591, -0.46026008, -1.58159576, -1.20297002],
       [ 0.24557476, -1.46420528, -0.60084069,  2.05590895],
       [ 0.37740972,  0.14641077, -1.00733322, -0.40083767],
       [ 1.02631697, -0.70967433,  0.41446421, -2.33088735]])

In [ ]:
#Where
results =np.where(arr<0, -2, 2 )  # arr ning manfiy elementlari -2 ga musbat elementlari esa 2 ga almashtirish
results

array([[ 2, -2, -2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2, -2],
       [ 2, -2,  2, -2]])