<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/2_1_3_Arr_Or_Pr_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy intellekt praktikum**
Ma'lumotlar tahlili
#Numpy kutubxonasi bilan ishlash

In [1]:
import numpy as np

Massivga yo'naltirilgan dasturlash

#Arifmetik Amallar

In [5]:
#data
arr1 = np.arange(6).reshape(2, 3) #0~6 gacha bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) #0~12 gacha bo'lgan elementlardan tashkil topgan array

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
#Ko'paytirish
arr1 * arr2 # arr1 ning elemtlarini arr2 ning mos ravishda ko'paytirib beradi.

array([[ 0,  7, 16],
       [27, 40, 55]])

In [15]:
#Bo'lish
arr2/arr1[1:] #arr1 ning elemtlarini arr2 ning mos ravishda bo'lib beradi. #0 dan tashqari hamma son bo'linadi

array([[2.  , 1.75, 1.6 ],
       [3.  , 2.5 , 2.2 ]])

In [16]:
#Qo'shish
arr1 + arr2  #arr1 ning elemtlarini arr2 ning mos ravishda qo'shib beradi beradi.

array([[ 6,  8, 10],
       [12, 14, 16]])

In [17]:
#Ayiruv
arr2 - arr1  #arr1 ning elemtlarini arr2 ning mos ravishda ayirib beradi.

array([[6, 6, 6],
       [6, 6, 6]])

In [24]:
#Kvadratga oshirish(square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [27]:
#Kvadrat ildizga (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])