<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/6_dars_malumotlar_turi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Science va Suniy intellekt praktikumi**
# Malumotlar tahlili.
2.1. Numpy kutubxonasi bilan ishlash

In [1]:
import numpy as np

2.1.1. N-O'lchovli massivlarga ishlov berish
Malumot turlari

Massivlar yaratishda malumot turlarini aniq kiritish , malumot turlarini aniqlash , bir turdagi malumot turidan ikkinchi turdagi malumot turiga o`tish.

In [4]:
arr1 = np.array([1, 2, 3, 4], dtype=np.float64) # bu float64 ma'lumotlar turiga ega massiv
arr1

array([1., 2., 3., 4.])

In [5]:
arr2 = np.array([1, 2, 3, 4], dtype= np.int32) # bu int32 ma'lumotlar turiga ega massiv
arr2

array([1, 2, 3, 4], dtype=int32)

`dtype` methodi bilan istalgan massivni va arrayni ma`lumot turini bilishimiz mumkun

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

#Bir turdagi ma'lumot turidan boshqasiga o'girish

In [8]:
arr = np.array([1, 2, 3, 4]) #int64
arr

array([1, 2, 3, 4])

In [9]:
arr.dtype

dtype('int64')

`astype` methodi

In [11]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

In [12]:
float_arr.dtype

dtype('float64')

#**`Diqqat` Birinchi ma'lumot turidan ikinchi ma'lumot turiga o'tayotganda ehtiyot bo'ling , chunki ma'lumot yo'toshingiz mumkun. ya'ni float dan int ga o'tishda.**

In [13]:
data = np.array([1.5, 2.5, 3.5, 4.5]) #float64
data

array([1.5, 2.5, 3.5, 4.5])

In [14]:
data.dtype

dtype('float64')

In [17]:
int_data = data.astype(np.int64)
int_data

array([1, 2, 3, 4])

In [18]:
int_data.dtype

dtype('int64')

#Xulosa `float` ma'lumot turidan `int` ma'lumot turiga o'tganimizda bizda ma'lumotlar yo'qoldi