<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/8_dars_Indekslash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy Intellekt Praktikum**

#Malumotlar tahlili


In [4]:
import numpy as np


#**N-O'lchamli massiv (array)larga ishlov berish**
Indeks va kesib olish asoslari

In [5]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
arr[0]

10

In [7]:
arr[1]

20

In [8]:
arr[2]

30

In [9]:
arr[-2] # 3 dan 5 gacha bo'lgan elementlarni kesib olib qaytaradi

80

In [10]:
arr[3:5]

array([40, 50])

#Numpy kutubxonasida massivning kesib olingan qismiga o`zgartirish kiritilinsa, asosiy manba massivga ta'sir qiladi.

In [11]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0 
sliced_arr

array([0, 0])

In [12]:
arr


array([10, 20, 30,  0,  0, 60, 70, 80, 90])

#**Copy usuli**

In [13]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
sliced_arr1 = arr[3:5].copy()
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [15]:
arr1


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#**2 O'lchamli (2d array) massivlarda indeks va kesib olish**

In [18]:
arr2d = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[2, 0]

7

In [23]:
arr2d[1, 2]

6

In [24]:
arr2d[2, 1]

8

#**2-O'lchamli massivlarning bir nechta elementlarini kesib olish**

In [25]:
sl_arr2d = arr2d[2, 1:3]
sl_arr2d

array([8, 9])

#**3 O'lchamli massivlarni indeks va kesib olish**

In [26]:
# 3D array

arr3d = np.array([[[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]],
                  
                  [[9, 10, 11],
                  [12, 13, 14],
                  [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])

arr3d
                   

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr3d[0][2, 1]

7

In [29]:
arr3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [30]:
arr3d[1][2, 2]

17

In [31]:
arr3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [33]:
arr3d[2][1, 0]

21