<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/9_dars_Boolen_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy Intellekt Praktikum**
#Ma'lumotlar tahlili
Numpy kutubxonasi bilan ishlash

In [7]:
import numpy as np

#2.1.1.N-O'lchovli massiv(array)larga ishlov berish 
Boolen Indekslash

In [8]:
#Ismlar 

names = np.array(['Muhriddin', 'Elyor', 'Husan', 'Elyor', 'Xurshid', 'Bobojon', 'Muhriddin'])
names

array(['Muhriddin', 'Elyor', 'Husan', 'Elyor', 'Xurshid', 'Bobojon',
       'Muhriddin'], dtype='<U9')

In [9]:
#data 

data = np.random.randn(7, 4)
data

array([[ 2.42347192, -0.12711368, -0.81393456,  0.43563754],
       [ 2.06139399, -2.14115339, -0.14142953,  0.93783161],
       [-2.79721848,  0.10757069,  0.70364013, -0.01792036],
       [ 1.46812742,  0.36474272,  0.38171072,  0.59352869],
       [-2.99068973, -0.03615072,  0.56312294, -0.10895767],
       [ 0.02433981, -0.15074425, -0.71427736,  2.43438917],
       [ 2.03586876, -0.45021266, -0.06457745,  0.2045676 ]])

#**

In [10]:
names == 'Muhriddin'

array([ True, False, False, False, False, False,  True])

In [11]:
names == 'Elyor'

array([False,  True, False,  True, False, False, False])

In [12]:
data[names == 'Muhriddin'] # Muhriddinga tegishli barcha ma'lumotlarni chiqarib olish

array([[ 2.42347192, -0.12711368, -0.81393456,  0.43563754],
       [ 2.03586876, -0.45021266, -0.06457745,  0.2045676 ]])

In [13]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni chiqarib olish

array([[ 2.06139399, -2.14115339, -0.14142953,  0.93783161],
       [ 1.46812742,  0.36474272,  0.38171072,  0.59352869]])

In [14]:
data[names == 'Muhriddin', 2:] # Muhriddinga tegishli oxirgi ikta ustundagi ma'lumotlarni chiqarib olish

array([[-0.81393456,  0.43563754],
       [-0.06457745,  0.2045676 ]])

In [15]:
data[names == 'Elyor', 2:] # Elyorga tegishli oxirgi ikkita ustundagi ma'lumotlarni chiqarib olish 

array([[-0.14142953,  0.93783161],
       [ 0.38171072,  0.59352869]])

In [18]:
print(names)
print(data)

['Muhriddin' 'Elyor' 'Husan' 'Elyor' 'Xurshid' 'Bobojon' 'Muhriddin']
[[ 2.42347192 -0.12711368 -0.81393456  0.43563754]
 [ 2.06139399 -2.14115339 -0.14142953  0.93783161]
 [-2.79721848  0.10757069  0.70364013 -0.01792036]
 [ 1.46812742  0.36474272  0.38171072  0.59352869]
 [-2.99068973 -0.03615072  0.56312294 -0.10895767]
 [ 0.02433981 -0.15074425 -0.71427736  2.43438917]
 [ 2.03586876 -0.45021266 -0.06457745  0.2045676 ]]


In [20]:
mask = (names == 'Muhriddin') | (names == 'Elyor') # "|" or(yoki)
mask

array([ True,  True, False,  True, False, False,  True])

In [21]:
data[mask] # Muhriddin va Elyorga tegishli ma`lumotlarni ajratib olish

array([[ 2.42347192, -0.12711368, -0.81393456,  0.43563754],
       [ 2.06139399, -2.14115339, -0.14142953,  0.93783161],
       [ 1.46812742,  0.36474272,  0.38171072,  0.59352869],
       [ 2.03586876, -0.45021266, -0.06457745,  0.2045676 ]])

In [22]:
data

array([[ 2.42347192, -0.12711368, -0.81393456,  0.43563754],
       [ 2.06139399, -2.14115339, -0.14142953,  0.93783161],
       [-2.79721848,  0.10757069,  0.70364013, -0.01792036],
       [ 1.46812742,  0.36474272,  0.38171072,  0.59352869],
       [-2.99068973, -0.03615072,  0.56312294, -0.10895767],
       [ 0.02433981, -0.15074425, -0.71427736,  2.43438917],
       [ 2.03586876, -0.45021266, -0.06457745,  0.2045676 ]])

In [23]:
data[data<0] = 0
data

array([[2.42347192, 0.        , 0.        , 0.43563754],
       [2.06139399, 0.        , 0.        , 0.93783161],
       [0.        , 0.10757069, 0.70364013, 0.        ],
       [1.46812742, 0.36474272, 0.38171072, 0.59352869],
       [0.        , 0.        , 0.56312294, 0.        ],
       [0.02433981, 0.        , 0.        , 2.43438917],
       [2.03586876, 0.        , 0.        , 0.2045676 ]])