<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/_12_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science praktikum**
Ma'lumotlar tahlili
#Numpy kutubxonasi bilan ishlash



In [2]:
import numpy as np

#Unary funksiyalar (bitta argument qabul qiluvchi funksiya)

`sqrt` `square` `exp` `log` `modf` `sign` `isnan` funksiya ko'rib chiqamiz

In [3]:
arr = np.arange(10) # 0~10 gacha bo'lgan elementlardan iborat bo'lgan massivni qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`sqrt` massivning xar bir elementini kvadrat ildizini qaytaradi

In [4]:
np.sqrt(arr) # arr nomli massivning barcha elementlaridan kv ildiz qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

`square` massivning har bir elementini kvadratga oshiradi

In [5]:
np.square(arr) # arr nomli massivning barcha elementini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
#np.square(arr).reshape(5, 2)
#darsdan tashqari idea 

`exp` massivning har bir elementini kvadratga oshiradi 


In [7]:
np.exp(arr) # arr nomli massivning barcha elementkarini eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

`log` massivning har bir massivning logarifmini hisoblaydi

In [8]:
np.log(arr)  # arr nomli massivning barcha elementlarini logarifmini hisoblaydi

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
arr1 = np.random.randn(6)
arr1

array([-0.21088719,  0.38077524, -0.18921467, -0.69367874,  1.1661168 ,
       -1.42015958])

In [10]:
qoldiq, butun = np.modf(arr1) # 6ta eelementdan iborat taxminiy qiymatlarga ega massiv

In [11]:
print(butun)
print(qoldiq)

[-0.  0. -0. -0.  1. -1.]
[-0.21088719  0.38077524 -0.18921467 -0.69367874  0.1661168  -0.42015958]


`sign` funksiyasi massiv elementlarini qiymat manfiy bo'lsa `-1` va aksincha musbat bo'lsa `1` ni qaytaradi

In [12]:
np.sign(arr1) # arr1 massivining elementlari ishoralarini `-1` va `1` ko'rinishida qaytaradi

array([-1.,  1., -1., -1.,  1., -1.])

`isnan` massivning elemtlarida NaN funksiyasi bo'lsa True va aksincha bo'lmasa False qaytaradi

In [13]:
arr1

array([-0.21088719,  0.38077524, -0.18921467, -0.69367874,  1.1661168 ,
       -1.42015958])

In [14]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [15]:
arr1[0] = np.NaN # 0- elementimizni NaN GA Almashtirish

In [16]:
arr1

array([        nan,  0.38077524, -0.18921467, -0.69367874,  1.1661168 ,
       -1.42015958])

In [17]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary (ikkita argument qabul qiluvchi funksiyalar)

`add`, `multiply`, `maximum` funksiyalarini ko'rib chiqamiz

`add` ikkita massivning mos elemtlarini qo'shadi

In [18]:
# 2 ta massiv yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [19]:
arr2

array([-0.06287349,  0.82472051, -0.03264978,  0.60437929, -0.77349889,
        0.8563972 ])

In [20]:
arr3

array([ 1.90888255, -0.73108957, -0.87273529, -0.80921877,  0.72102842,
        1.46334799])

In [21]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi 
#shunga o'xshagan method 
arr2 + arr3

array([ 1.84600906,  0.09363094, -0.90538507, -0.20483948, -0.05247047,
        2.31974518])

`multiply` ikkita massivning elementlarini mos ravishda ko'paytiradi

In [22]:
arr2

array([-0.06287349,  0.82472051, -0.03264978,  0.60437929, -0.77349889,
        0.8563972 ])

In [23]:
arr3

array([ 1.90888255, -0.73108957, -0.87273529, -0.80921877,  0.72102842,
        1.46334799])

In [24]:
np.multiply(arr2, arr3) # arr2 va arr3 ning mos elemtlarini ko'paytiradi

array([-0.12001812, -0.60294456,  0.02849462, -0.48907506, -0.55771469,
        1.25320711])

In [25]:
np.maximum(arr2, arr3) # arr2 va arr3 ni taqqoslab kattasini chiqarib beradi

array([ 1.90888255,  0.82472051, -0.03264978,  0.60437929,  0.72102842,
        1.46334799])