<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science
# Ma`lumotlar tahlili
2.1. Numpy kutubxonasi bilan ishlash
NUmpy kutubxonasini chaqirib olish 

In [1]:
import numpy as np


2.1.1. N-O`lchamli massiv(array)larga ishlov berish

Numpyda massiv yaratishning eng oson yo`llaridan biri bu array funksiyasi yordamida amalga oshiriladi. Va ushbu funksiya xar qanday turdagi ketma ket ma`lumotlarni qabul qilib, uni yangi numpy arrayga o`girib beradi

In [2]:
Data1 = [5.5 , 7, 9, 2.9] # list
arr1 = np.array(Data1) #Array1

In [3]:
arr1

array([5.5, 7. , 9. , 2.9])

In [4]:
Data2 = [3.3 , 5.0 , 6.2 , 9] #tuple
arr2 = np.array(Data2) #Array2


In [5]:
arr2

array([3.3, 5. , 6.2, 9. ])

In [6]:
arr2.ndim #arr2 ning o'lchami

1

#Massiv O`lchami

 .ndim methodi massiv(array)ni o`lchamini aniqlash mumkun

In [7]:
arr1.ndim # array1 ning o`lchami
#Bu usul orqali massivni o`lchamini aniqlash mumkin

1

*IKKI VA UNDAN KATTA O`LCHAMLI MASSIVLAR HAQIDA *
Biz List ichidagi Listdan turidan foydalanamiz bu ingiliz tilida nested list deyiladi.

In [8]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # nested list
arr3 = np.array(data3) #array3

In [9]:
arr3.ndim


2

*SIZE VA SHAPE METHODLARI*

---

-Shape methodi massivning qator va ustunlar sonini ko`rsatsa

-size methodi esa massivlardagi elementlar sonini namoyon etadi.

In [10]:
arr3.shape # qator va ustunlar sonini ko`rsatadi 

(2, 4)

Bu koddan ma`lumki 2 qator 4 ta ustun bor    

# Size methodi funksiyada to`liq nechta raqam borligini ko`rsatadi.

In [11]:
arr3.size #array3ning elementlar soni

8

# N-O'lchamli massivlarni yaratishning boshqa usullari mavjud:

-zeros va ones funksiyalari yordamida massivlar yaratish:


In [12]:
arr4 = np.zeros((2,4)) # barcha elementlari 0 ga teng bo`lgan (2, 4) massivlarni yaratadi.
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr5 =np.ones((2,4)) # barcha elementlari 1 ga teng bo'lgan (2, 4) massivlarni yaratadi
arr5


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arrange funksiyasi yordamida yaratish.


In [16]:
arr6 = np.arange(3, 30, 5)  #3 dan 30 gacha bo`lgan qiymatlarni 5 qadam bilan massivlarga joylab beradi.
arr6

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
arr7 = np.arange(20) # 0 dan 20 gacha bo`lgan qiymatlarni 1 qadam bilan massivlarga joylab beradi.