<a href="https://colab.research.google.com/github/qodirovmuhriddin/Data_Science/blob/main/_5_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science praktikumi**

In [1]:
import numpy as np

`reshape` methodi

In [14]:
A=np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

`Transpose`

In [15]:
A.T # A massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

`Swaping axes`

In [21]:
A.swapaxes(1, 0)  # A massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

`Transpose`ning ishlatilishiga bir misol AA^T

In [22]:
np.dot(A, A.T)# AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])